stages:
    - test
    - build

ars-test-job:
    stage: test
    script:
        - cd Ars
        - echo "Ars doesn't test for now."
        - cd ../
    only:
        - master

cerebrum-test-job:
    stage: test
    script:
        - cd Cerebrum
        - dotnet test
        - cd ../
    only:
        - master
      
ars-build-job:
    stage: build
    script:
        - cd Ars
        - echo "Ars doesn't build for now."
        - cd ../
    only:
        - master
        - tags

cerebrum-build-job:
    stage: build
    script:
        - cd Cerebrum/CSharpTest
        - dotnet build CSharpTest.csproj -c Release
        - cd ../../
        - mv Cerebrum/CSharpTest/bin/Release/ Artifact
    artifacts:
        paths: 
            - Artifact/
        name: "Cerebrum-$CI_COMMIT_REF_NAME"
    only:
        - master
        - tags